config/routes.rb
Rails.application.routes.draw do
  resources :bee_logs

end

app/models/bee_log.rb
class BeeLog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bee_logs_controller.rb
class BeeLogsController < ApplicationController
  before_action :set_bee_log, only: [:show, :edit, :update, :destroy]

  # GET /bee_logs
  # GET /bee_logs.json
  def index
    @bee_logs = BeeLog.all
  end

  # GET /bee_logs/1
  # GET /bee_logs/1.json
  def show
  end

  # GET /bee_logs/new
  def new
    @bee_log = BeeLog.new
  end

  # GET /bee_logs/1/edit
  def edit
  end

  # POST /bee_logs
  # POST /bee_logs.json
  def create
    @bee_log = BeeLog.new(bee_log_params)

    respond_to do |format|
      if @bee_log.save
        format.html { redirect_to @bee_log, notice: 'Bee log was successfully created.' }
        format.json { render :show, status: :created, location: @bee_log }
      else
        format.html { render :new }
        format.json { render json: @bee_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bee_logs/1
  # PATCH/PUT /bee_logs/1.json
  def update
    respond_to do |format|
      if @bee_log.update(bee_log_params)
        format.html { redirect_to @bee_log, notice: 'Bee log was successfully updated.' }
        format.json { render :show, status: :ok, location: @bee_log }
      else
        format.html { render :edit }
        format.json { render json: @bee_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bee_logs/1
  # DELETE /bee_logs/1.json
  def destroy
    @bee_log.destroy
    respond_to do |format|
      format.html { redirect_to bee_logs_url, notice: 'Bee log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bee_log
      @bee_log = BeeLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bee_log_params
      params.require(:bee_log).permit(:temperature, :humidity, :colony_name, :longitude, :latitude, :status, :monitor_data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bee_logs_helper.rb
module BeeLogsHelper
end

app/views/bee_logs/_form.html.erb
<%= form_for(@bee_log) do |f| %>
  <% if @bee_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bee_log.errors.count, "error") %> prohibited this bee_log from being saved:</h2>

      <ul>
      <% @bee_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_area :temperature %>
  </div>
  <div class="field">
    <%= f.label :humidity %><br>
    <%= f.text_field :humidity %>
  </div>
  <div class="field">
    <%= f.label :colony_name %><br>
    <%= f.text_area :colony_name %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :monitor_data %><br>
    <%= f.text_area :monitor_data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bee_logs/edit.html.erb
<h1>Editing Bee Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @bee_log %> |
<%= link_to 'Back', bee_logs_path %>

app/views/bee_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bee Logs</h1>

<table>
  <thead>
    <tr>
      <th>Temperature</th>
      <th>Humidity</th>
      <th>Colony name</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Status</th>
      <th>Monitor data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bee_logs.each do |bee_log| %>
      <tr>
        <td><%= bee_log.temperature %></td>
        <td><%= bee_log.humidity %></td>
        <td><%= bee_log.colony_name %></td>
        <td><%= bee_log.longitude %></td>
        <td><%= bee_log.latitude %></td>
        <td><%= bee_log.status %></td>
        <td><%= bee_log.monitor_data %></td>
        <td><%= link_to 'Show', bee_log %></td>
        <td><%= link_to 'Edit', edit_bee_log_path(bee_log) %></td>
        <td><%= link_to 'Destroy', bee_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bee log', new_bee_log_path %>

app/views/bee_logs/new.html.erb
<h1>New Bee Log</h1>

<%= render 'form' %>

<%= link_to 'Back', bee_logs_path %>

app/views/bee_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Temperature:</strong>
  <%= @bee_log.temperature %>
</p>

<p>
  <strong>Humidity:</strong>
  <%= @bee_log.humidity %>
</p>

<p>
  <strong>Colony name:</strong>
  <%= @bee_log.colony_name %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @bee_log.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @bee_log.latitude %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bee_log.status %>
</p>

<p>
  <strong>Monitor data:</strong>
  <%= @bee_log.monitor_data %>
</p>

<%= link_to 'Edit', edit_bee_log_path(@bee_log) %> |
<%= link_to 'Back', bee_logs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keep</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>